version: "3"
services:
  api:
    container_name: habit_api
    image: habit_api
    build: .
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - db
    command: bash -c "sleep 3s npx jest --runInBand --verbose"
  db:
    container_name: habit_db
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    env_file: .env
    volumes:
      - habit-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - NODE_ENV=test
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test

volumes:
  habit-db-data:
