version: "3"
services:
  api:
    container_name: habit_api
    image: habit_api
    build: .
    env_file: .env
    environment:
      - NODE_ENV=test
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - db
    command: >
      bash -c "npx jest --runInBand --verbose --coverage
      --collectCoverage --coverageReporters=html --forceExit"
  db:
    container_name: habit_db
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    env_file: .env
    volumes:
      - habit-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  habit-db-data:
